resolver: lts-7.3
compiler: ghcjs-0.2.1.9007003_ghc-8.0.1

setup-info:
  ghcjs:
    source:
      ghcjs-0.2.1.9007003_ghc-8.0.1:
          url: http://ghcjs.tolysz.org/ghc-8.0-2016-10-11-lts-7.3-9007003.tar.gz
          sha1: 3196fd5eaed670416083cf3678396d02c50096de

packages:
- '.'

- location:
    git: https://github.com/reflex-frp/reflex
    commit: 2fe0f566f8d6b6eceb178a85516643390111bb83
  extra-dep: true
- location:
    git: https://github.com/reflex-frp/reflex-dom
    commit: 706ab47df9729bdc5c4ac3f4d8dfd4661d9f6e1a
  subdirs:
    - reflex-dom
    - reflex-dom-core
  extra-dep: true

extra-deps:
- ref-tf-0.4.0.1
- prim-uniq-0.1.0.1
- dependent-map-0.2.4.0
- zenc-0.1.1
- ghcjs-dom-0.8.0.0
- ghcjs-dom-jsffi-0.8.0.0
- jsaddle-0.8.3.2
